# Your Name or Company
title: Jessica Appelbaum

# Description of your website. This is used for social sharing.
description:  Software Engineer

# A brief blurb about yourself
content: Software Engineer | Full-Stack | Front-End | Design Systems

# Add your social links
social:
  - platform: GitHub
    url: https://github.com/jessapp
  - platform: LinkedIn
    url: https://www.linkedin.com/in/jessapp/
  - platform: Medium
    url: https://medium.com/@jess.appelbaum


# General settings
markdown: kramdown

#### LAYOUT OPTIONS #####

# Full layout
full_text_position: right # left, right or center
